#pragma once

#define CONFIG_DISK_NAME "db"
// 0 = LRU
#define CONFIG_DISK_EVICTION_POLICY 0
#define CONFIG_DISK_SURFACES 10
#define CONFIG_DISK_TRACKS 10
#define CONFIG_DISK_SECTORS 50
#define CONFIG_DISK_BYTES 1 << 12
#define CONFIG_DISK_SECTOR_BLOCKS 4
#define CONFIG_DISK_NFRAMES 8